{{- if .Values.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "python-app.serviceAccountName" . }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
