apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name}}
  labels:
    app: {{ .Values.name}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name}}
  replicas: {{ .Values.replicas}}
  strategy:
    type: {{ .Values.strategy.type}}
  template:
    metadata:
      labels:
        app: {{ .Values.name}}
    spec:
      containers:
        - name: {{ .Values.name}}
          image: {{ .Values.image}}
          ports:
            - containerPort: {{ .Values.port}}
              protocol: {{ .Values.protocol}}